extraction:
  cpp:
    after_prepare: 
      - python report.py 83
  cobol:
    after_prepare: 
      - python report.py 83
  csharp:
    after_prepare: 
      - python report.py 83
  java:
    after_prepare: 
      - python report.py 83
  javascript:
    after_prepare: 
      - python report.py 83
  python:
    after_prepare: 
      - python report.py 83
